// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Intake.h"
#include "../RobotMap.h"
#include "../Commands/StopIntakeDown.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Intake::Intake() : Subsystem("Intake") {
		Lift = RobotMap::intakeLift;
		Wheels = RobotMap::intakeWheels;
		LiftEncoder = RobotMap::intakeLiftEncoder;
		LiftEncoder->Reset();
		BallHeld=false;
}

void Intake::InitDefaultCommand() {
	SetDefaultCommand(new StopIntakeDown());
}


// Put methods for controlling this subsystem
// here. Call these from Commands.
	void Intake::Up(double s){
		Lift->Set(-s);
	}
	void Intake::Down(double s){
		Lift->Set(s);
	}
	void Intake::In(double s){
		Wheels->Set(s);
	}
	void Intake::Out(double s){
		Wheels->Set(-s);
	}

	double Intake::GetEncoder(){
		return LiftEncoder->Get();
	}
	bool Intake::GetBallHeld(){
		return BallHeld;
	}
	void Intake::SetBallHeld(bool held){
			BallHeld = held;
	}
